config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	# resources :users do
	# 	resources :cardlists do
	# 		resources :cards
	# 		patch 'cards/:id/check' => 'cards#update2' , as: 'update2'
	# 	end
	# end

    get 'cardlists/:user_id/index' => 'cardlists#index' , as: 'cardlists_index'
    post 'cardlists/:user_id' => 'cardlists#create'
    get 'cardlists/index_all_users' => 'cardlists#index_all_users', as: 'cardlists_index_all_users'

	resources :users
	resources :cardlists do
		resource :favorites, only: [:create, :destroy]
		resources :cards
		patch 'cards/:id/check' => 'cards#update2' , as: 'update2'
	end

	root :to => 'root#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

	belongs_to :cardlist


end

app/models/cardlist.rb
class Cardlist < ApplicationRecord

	belongs_to :user
	has_many :cards, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :cardlist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cardlists, dependent: :destroy
  has_many :favorites, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:user_name]

  validates :user_name, presence: true, length: {in:1..10}

  attachment :image

 def email_required?
   false
 end
 def email_changed?
   false
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_up_path_for(resource)
		user_path(resource)
	end

	def after_sign_in_path_for(resource)
		user_path(resource)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    end
end

app/controllers/cardlists_controller.rb
class CardlistsController < ApplicationController

  before_action :authenticate_user!

  def new
  	@cardlist = Cardlist.new
  end

  def create
  	cardlist = Cardlist.new(cardlist_params)
    cardlist.user_id = current_user.id
  	cardlist.save
  	redirect_to cardlists_index_path(current_user.id)
  end

  def index
    @user = User.find(params[:user_id])
    @cardlist = Cardlist.new
  	@cardlists = @user.cardlists
  end

  def index_all_users
    @cardlists = Cardlist.where.not(user_id: current_user.id)
  end

  def show
  	@cardlist = Cardlist.find(params[:id])
    @cards = @cardlist.cards.where(check: false)
    @cardspage = @cards.page(params[:page]).per(10).reverse_order
  end

  def edit
  	@cardlist = Cardlist.find(params[:id])
  	@card = Card.new
    @cards = @cardlist.cards.page(params[:page]).per(10).reverse_order
  end

  def update
  	cardlist = Cardlist.find(params[:id])
  	cardlist.update(cardlist_params)
  	redirect_to edit_cardlist_path(cardlist.id)
  end

  def destroy
  	cardlist = Cardlist.find(params[:id])
  	cardlist.destroy
  	redirect_to cardlists_index_path(current_user.id)
  end

  private
  def cardlist_params
  	params.require(:cardlist).permit(:cardlist_name, :user_id)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
  	@card = Card.new
  end

  def create
  	card = Card.new(card_params)
  	cardlist = Cardlist.find(params[:cardlist_id])
  	card.cardlist_id = cardlist.id
  	card.save
  	redirect_to edit_cardlist_path(cardlist.id)
  end

  def index
  end

  def show
  end

  def edit
  	@card = Card.find(params[:id])
  	@cardlist = Cardlist.find(params[:id])
  end

  def update
  	card = Card.find(params[:id])
  	card.update(card_params)
  	cardlist = Cardlist.find(params[:cardlist_id])
  	redirect_to edit_cardlist_path(cardlist.id)
  end

  def update2
  	cardlist = Cardlist.find(params[:cardlist_id])
  	card = Card.find(params[:id])
  	if card.check == false
	   card.update(check: true)
  	else
	   card.update(check: false)
  	end
  	redirect_to edit_cardlist_path(cardlist.id)
  end

  def destroy
  	card = Card.find(params[:id])
  	card.destroy
  	cardlist = Cardlist.find(params[:cardlist_id])
  	redirect_to edit_cardlist_path(cardlist.id)
  end

  private
  def card_params
  	params.require(:card).permit(:card_name, :no, :front, :back, :check, :cardlist_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		cardlist = Cardlist.find(params[:cardlist_id])
		favorite = current_user.favorites.new(cardlist_id: cardlist.id)
		favorite.save
		redirect_to cardlists_index_all_users_path
	end

	def destroy
		cardlist = Cardlist.find(params[:cardlist_id])
		favorite = current_user.favorites.find_by(cardlist_id: cardlist.id)
		favorite.destroy
		redirect_to cardlists_index_all_users_path
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	user.update!(user_params)
  	redirect_to user_path(user.id)
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cardlists_helper.rb
module CardlistsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cardlists/edit.html.erb
<h2>カードリスト編集</h2>

<%= form_for (@cardlist) do |f| %>
<%= f.text_field :cardlist_name, :class => 'form' %>
<%= f.submit "更新" %>
<%end%>
<br>

<%= form_for [@cardlist, @card] do |c| %>
<%= c.text_area :front, :size => "40x5", :class => 'form' %>
<%= c.text_area :back, :size => "40x5", :class => 'form' %>
<%= c.submit "登録" %>
<%end%>
<br>

<h4>
<span>覚えたカード <%= num1 = @cardlist.cards.where(check: 'true').count %>枚</span>
<br>
<span>全てのカード <%= num2 = @cardlist.cards.count %>枚</span>
</h4>

<% num = (num1.to_f / num2).round(2)  %>
<% num = (num*100).to_i %>

<div class="progress">
	<div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar" style="width:<%= num %>%;">
		<%= num %>%
	</div>
</div>

<table class="table table-hover">
	<thead>
		<tr>
			<th>表</th>
			<th>裏</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @cards.each do |card| %>
		    <%= form_for ([@cardlist, card]) do |f|%>
				<tr>
					<td><%= f.text_area :front, :class => 'form2' %></td>
					<td><%= f.text_area :back, :class => 'form2' %></td>
					<td><%= f.submit "更新" %></td>
					<td>
					  <%= link_to "削除", cardlist_card_path(@cardlist.id, card.id), method: :delete, "data-confirm"=>"本当に削除しますか？" %>
					</td>
					<td>
				      <% if card.check == false %>
				         <%= link_to cardlist_update2_path(@cardlist.id, card.id),method: :patch do %>
					     <span class="glyphicon glyphicon-star star2" aria-hidden="true"></span>
				         <% end %>
				      <% else %>
				         <%= link_to cardlist_update2_path(@cardlist.id, card.id),method: :patch do %>
					     <span class="glyphicon glyphicon-star star1" aria-hidden="true"></span>
				         <% end %>
				      <% end %>

					</td>
				</tr>
			<% end %>
        <% end %>
	</tbody>

</table>
	<%= paginate @cards, class: "pagenate" %>

	<p><%= link_to cardlist_path(@cardlist.id), class: 'btn btn-default btn-lg btn-block' do %>
	<i class="fa fa-arrow-left"></i>
	学習
	<% end %>
	</p>

app/views/cardlists/index.html.erb
<h1>マイカードリスト</h1>

<% if current_user == @user %>

<div class="text">
	<%= form_for (@cardlist) do |c| %>
	<p>カードリスト名</p>
	<%= c.text_field :cardlist_name, :class => 'form'  %>
	<%= c.submit '登録' %>
	<% end %>
</div>

	<table class="table table-hover">
		<thead>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody class="text">
			<% @cardlists.each do |c| %>
			<tr>
				<td><%= c.cardlist_name %></td>
				<td><span class="glyphicon glyphicon-heart heart1" aria-hidden="true"><%= c.favorites.count %></span></td>
				<td><%= link_to "学習", cardlist_path(c.id) %></td>
				<td><%= link_to "編集", edit_cardlist_path(c.id) %></td>
				<td><%= link_to "削除", cardlist_path(c.id), method: :delete, "data-confirm"=>"本当に削除しますか？" %></td>
			</tr>
			<%end%>
		</tbody>
	</table>

<% else %>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>カードリスト名</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @cardlists.each do |c| %>
			<tr>
				<td><%= c.cardlist_name %></td>
				<td><%= link_to "学習", cardlist_path(c.id) %></td>
			</tr>
			<%end%>
		</tbody>
	</table>

<% end %>

app/views/cardlists/index_all_users.html.erb
<h1>みんなのカードリスト</h1>

<table class="table table-hover text">
		<thead>
			<tr>
				<th>カードリスト名</th>
				<th>ユーザー名</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @cardlists.each do |card| %>
			<tr>
				<td><%= card.cardlist_name %></td>
				<td><%= link_to "学習", cardlist_path(card.id) %></td>
				<td>
					<% if card.favorited_by?(current_user) %>
						 <%= link_to cardlist_favorites_path(card.id), method: :delete do %>
						 <span class="glyphicon glyphicon-heart heart1" aria-hidden="true"></span>
						 <%= card.favorites.count %>
						 <% end %>
					<% else %>
						 <%= link_to cardlist_favorites_path(card.id), method: :post do %>
						 <span class="glyphicon glyphicon-heart heart2" aria-hidden="true"></span>
						 <%= card.favorites.count %>
						 <% end %>
					<% end %>
				</td>
			</tr>
			<%end%>
		</tbody>
	</table>

app/views/cardlists/new.html.erb
<h1>Cardlists#new</h1>

<%= form_for (@cardlist) do |c| %>
<p>カードリスト名</p>
<%= c.text_field :cardlist_name %>
<%= c.submit '登録' %>
<%end%>

<h2><%= link_to "カードリスト一覧へ", cardlists_path %></h2>

app/views/cardlists/show.html.erb
	<h1><%= @cardlist.cardlist_name %></h1>

<table class="table table-hover">
	<thead>
		<tr>
			<th>表</th>
			<th>裏</th>
		</tr>
	</thead>
	<tbody>
		<% @cardspage.each do |card|%>
		<tr>
			<td class="show-front"><%= simple_format(card.front) %></td>

			<td class="back">
				<div class="div-action">
				<%= simple_format(card.back) %>
				</div>
			</td>

		</tr>
		<%end%>
	</tbody>
</table>

<%= paginate @cardspage, class: "pagenate" %>

<% if @cardlist.user.id == current_user.id %>
	<p><%= link_to edit_cardlist_path(@cardlist.id), class: 'btn btn-default btn-lg btn-block' do %>
	<i class="fa fa-arrow-left"></i>
	カードリスト編集
	<% end %>
	</p>
<% else %>
<% end %>
<!-- <script>
	$(function(){
	$('.div-action').on('click', function()  {
	// $(this).toggleClass('background-color');

	if ($(this).hasClass('background-color')) {
		$(this).removeClass('background-color');
	} else {
		$(this).addClass('background-color');
	}

	});



    var $header = $('#top-head');
    // Nav Fixed
    $(window).scroll(function() {
        if ($(window).scrollTop() > 100) {
            $header.addClass('fixed');
        } else {
            $header.removeClass('fixed');
        }
    });
    // Nav Toggle Button
    $('#nav-toggle').click(function(){
        $header.toggleClass('open');
    });

});
</script> -->

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/index.html.erb
<h1>Cards#index</h1>
<p>Find me in app/views/cards/index.html.erb</p>

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/cards/show.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedCard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

</head>

<body class="all">
  <!-- ヘッダー -->
  <header id="top-head">
    <div class="inner">
      <div id="mobile-head">
        <h1 class="logo">RedCard</h1>
        <div id="nav-toggle">
          <div>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </div>
      <nav id="global-nav">
        <ul>
          <li>
            <a>
              <%= link_to user_path(current_user.id), class:'btn btn-default' do %>
              <span class="glyphicon glyphicon-user" aria-hidden="true"> マイページ</span>
              <% end %>
            </a>
          </li>
          <li>
            <a>
              <%= link_to cardlists_index_path(current_user.id), class:'btn btn-default' do %>
              <span class="glyphicon glyphicon-tags" aria-hidden="true"> マイカードリスト</span>
              <% end %>
            </a>
          </li>
          <li>
            <a>
              <%= link_to cardlists_index_all_users_path, class:'btn btn-default' do %>
              <span class="glyphicon glyphicon-tags" aria-hidden="true"> みんなのカードリスト</span>
              <% end %>
            </a>
          </li>
          <li>
            <a>
              <%= link_to destroy_user_session_path, method: :delete,"data-confirm"=>"ログアウトしますか？", :class => 'navbar-link', class:'btn btn-default' do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"> ログアウト</span>
              <% end %>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 col-xs-12">
        <br>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <div class="jumbotron jumbotron-extend">
<div class="container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-2">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>

app/views/layouts/root.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/top.html.erb
<div class="jumbotron jumbotron-extend">
<div class="container-fluid">
		<div class="row">
			<div class="col-md-5 col-md-offset-2 top1">

				<p>単語暗記サイト</p>
				<h1>RedCard</h1>

					<button type="button" class="btn btn-default"><%= link_to "ログイン", new_user_session_path %></button>

					<button type="button" class="btn btn-default"><%= link_to "新規登録", new_user_registration_path %></button>

			</div>
		</div>
	</div>
</div>

<div class="jumbotron top2">
<div class="container">
		<div class="row">
			<div class="col-md-6 picture-iphone">
				<%#= image_tag "picture3.jpg", :size => "300x600" %>
				<%= image_tag "/images/picture3.jpg", :size => "300x600" %>

			</div>
			<div class="col-md-6">
				<h2>赤い部分をクリックすると正解を確認できます。<br>
				<br>答えがわからなかった時は時間を置いて再度学習しましょう。</h2>
			</div>
		</div>
	</div>
</div>

<div class="jumbotron top2">
<div class="container">
		<div class="row">
			<div class="col-md-6 picture-iphone">
				<%#= image_tag "picture2.jpg", :size => "300x600" %>
				<%= image_tag "/images/picture2.jpg", :size => "300x600" %>
			</div>
			<div class="col-md-6">
				<h2>覚えたカードは表示させないようにできます。<br>
				<br>覚えたカードが学習の度に表示されると煩わしいものです。<br>
			    <br>時間を置いた後に確認しましょう。</h2>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>

<%= form_for (@user) do |f| %>
<table class="table">
	<tr>
		<th>ユーザー名</th>
		<td><%= f.text_field :user_name, :class => 'form' %></td>
	</tr>
	<tr>
		<th>メールアドレス</th>
		<td><%= f.email_field :email, :class => 'form' %></td>
	</tr>
	<tr>
		<th>イメージ</th>
		<td><%= f.attachment_field :image %></td>
	</tr>
</table>
<%=f.submit "完了"%>
<% end %>

<p><%= link_to user_path(@user.id), class: 'btn btn-default btn-lg btn-block' do %>
<i class="fa fa-arrow-left"></i>
戻る
<% end %>
</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

<table class="table table-hover">
	<thead>
		<tr>
			<th>ユーザー名<th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |users| %>
		<tr>
			<td><%= users.user_name %></td>
			<td><%= link_to "ああああ", cardlists_index_path(users.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<p><%#= link_to "ユーザー情報", user_path(@user.id) %></p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>マイページ</h1>

<table class="table">
	<tr>
		<th>ユーザー名</th>
		<td><%= @user.user_name %></td>
	</tr>
	<tr>
		<th>メールアドレス</th>
		<td><%= @user.email %></td>
	</tr>
	<tr>
		<th>イメージ</th>
		<td><%= attachment_image_tag @user, :image, :fill, 100, 100, format: 'jpeg' %></td>
	</tr>
</table>

<p><%= link_to edit_user_path(@user.id), class: 'btn btn-default btn-lg btn-block' do %>
<i class="fa fa-arrow-left"></i>
ユーザー情報の編集
<% end %>
</p>

<% if user_signed_in? %>
          <p>ログイン中　<%= current_user.user_name %>さん</p>
              <%= link_to destroy_user_session_path, method: :delete,"data-confirm"=>"ログアウトしますか？", :class => 'navbar-link', class:'btn btn-default' do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"> ログアウト</span>
              <% end %>
<% else %>
          <p><%= link_to 'ログイン', users_path %></p>
          <p><%= link_to '新規登録', new_user_registration_path %></p>
<% end %>

<div class="getout">
  <%= link_to "退会手続き", user_registration_path, method: :delete,"data-confirm"=>"本当に退会しますか？" %>
</div>